server:
  #port: 8083  
  servlet:
    context-path: /sample
    
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/mcq
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    

